### Get all person
GET http://localhost:3001/api/persons

### Delete person
DELETE http://localhost:3001/api/persons/2

### Add person
POST  http://localhost:3001/api/persons
Content-Type: application/json

  {
    "name": "Tran Dan",
    "number": "111-222-333"
  }